### PR TITLE
feat: make changelog filename configurable

### PR DESCRIPTION
**Pull request by juckerf**
Optional parameter `-f` or `--filename` is added to specify the name of the changelog file

### CODE REVIEW

**Comment by juckerf** [comment]
partly fixes  #1

**Comment by mogensen** [comment]
Hi @juckerf 

Thanks for the contribution!

I would love to merge this, if we can do it without the breaking change.
I know of multiple different applications that are already using this in automated pipelines, and I would hate to break them on next release.

/mogensen

**Comment by juckerf** [comment]
I changed the default filename back to `Changelog.md`, so now it should be non-breaking.
(I made a bit of a mess with the commits, so feel free to squash the PR for a clean history)

**Comment by mogensen** [comment]
Perfect! Thanks!

**Pull request merged**
